collections:
  authors:
    output: true

sass:
  load_paths:
    - _sass
    - vendor/bundle/gems/bootstrap-4.1.3/assets/stylesheets

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"